# -*- coding: utf-8 -*-
"""lst_y_cordenadas_galacticas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Knt9WCnEWDAzrTPx_WqPdg3riafTGwx5
"""

import numpy as np
from datetime import datetime, date

N = datetime.now().timetuple().tm_yday #Number of the day in the year

#Constant G = 6.6270444445 this constant is an arbitrary constant from the Astronomy Almanac 2023

Long = float(input('\nLongitude\n')) #Input longitude

#Long = -70.47 ###Chile
TD = input('\nInput date and hour in this format: MMDDAA HHMM.\n') #Input date and hour


MM = float(TD[0:2])
DD = float(TD[2:4])
AA = float(TD[4:6])
AA = AA+2000

hh = float(TD[7:9])+4   # In Chile is GMT -4 so i added 4 and GMT = UT making this code work//
                        # if you wanna use this code please check your local GMT or better just use UT//

mm = float(TD[9:11])
mm = mm/60
UT = hh+mm


GST = 6.6270444445 + 0.0657098245*N + 1.00273791*UT #Greenwicth  Sidereal Time

GST = GST % 24

Long = Long/15 # Longitude to hour
LST = GST+Long # Local Sideral Time

if LST < 0:
    LST = LST +24

#Lets order our time for a readable output

LSTmm = (LST - int(LST))*60
LSTss = (LSTmm - int(LSTmm))*60
LSThh = int(LST)
LSTmm = int(LSTmm)
LSTss = int(LSTss)

print ('\nLocal Sidereal Time %s:%s:%s \n\n' %(LSThh, LSTmm, LSTss))